# Generated by Django 4.0.6 on 2023-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_to',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
